import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono, notoSansKr } from '@/config/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable} ${notoSansKr.variable}`}>
      <body className="font-noto">{children}</body>
    </html>
  );
}
